In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

We're ready to build our first neural network. We will have multiple features we feed into our model, each of which will go through a set of perceptron models to arrive at a response which will be trained to our output.

Like many models we've covered, this can be used as both a regression or classification model.

First, we need to load our dataset. For this example we'll use The Museum of Modern Art in New York's [public dataset](https://media.githubusercontent.com/media/MuseumofModernArt/collection/master/Artworks.csv) on their collection.

In [2]:
artworks = pd.read_csv('https://media.githubusercontent.com/media/MuseumofModernArt/collection/master/Artworks.csv')

In [3]:
artworks.columns

Index(['Title', 'Artist', 'ConstituentID', 'ArtistBio', 'Nationality',
       'BeginDate', 'EndDate', 'Gender', 'Date', 'Medium', 'Dimensions',
       'CreditLine', 'AccessionNumber', 'Classification', 'Department',
       'DateAcquired', 'Cataloged', 'ObjectID', 'URL', 'ThumbnailURL',
       'Circumference (cm)', 'Depth (cm)', 'Diameter (cm)', 'Height (cm)',
       'Length (cm)', 'Weight (kg)', 'Width (cm)', 'Seat Height (cm)',
       'Duration (sec.)'],
      dtype='object')

We'll also do a bit of data processing and cleaning, selecting columns of interest and converting URL's to booleans indicating whether they are present.

In [4]:
# Select Columns.
artworks = artworks[['Artist', 'Nationality', 'Gender', 'Date', 'Department',
                    'DateAcquired', 'URL', 'ThumbnailURL', 'Height (cm)', 'Width (cm)']]

# Convert URL's to booleans.
artworks['URL'] = artworks['URL'].notnull()
artworks['ThumbnailURL'] = artworks['ThumbnailURL'].notnull()

# Drop films and some other tricky rows.
artworks = artworks[artworks['Department']!='Film']
artworks = artworks[artworks['Department']!='Media and Performance Art']
artworks = artworks[artworks['Department']!='Fluxus Collection']

# Drop missing data.
artworks = artworks.dropna()

In [5]:
artworks.head()

Artist Nationality  Gender  Date             Department  \
0               Otto Wagner  (Austrian)  (Male)  1896  Architecture & Design   
1  Christian de Portzamparc    (French)  (Male)  1987  Architecture & Design   
2                Emil Hoppe  (Austrian)  (Male)  1903  Architecture & Design   
3           Bernard Tschumi          ()  (Male)  1980  Architecture & Design   
4                Emil Hoppe  (Austrian)  (Male)  1903  Architecture & Design   

  DateAcquired   URL  ThumbnailURL  Height (cm)  Width (cm)  
0   1996-04-09  True          True      48.6000    168.9000  
1   1995-01-17  True          True      40.6401     29.8451  
2   1997-01-15  True          True      34.3000     31.8000  
3   1995-01-17  True          True      50.8000     50.8000  
4   1997-01-15  True          True      38.4000     19.1000

## Building a Model

Now, let's see if we can use multi-layer perceptron modeling (or "MLP") to see if we can classify the department a piece should go into using everything but the department name.

Before we import MLP from SKLearn and establish the model we first have to ensure correct typing for our data and do some other cleaning.

In [6]:
# Get data types.
artworks.dtypes

Artist           object
Nationality      object
Gender           object
Date             object
Department       object
DateAcquired     object
URL                bool
ThumbnailURL       bool
Height (cm)     float64
Width (cm)      float64
dtype: object

The `DateAcquired` column is an object. Let's transform that to a datetime object and add a feature for just the year the artwork was acquired.

In [7]:
artworks['DateAcquired'] = pd.to_datetime(artworks.DateAcquired)
artworks['YearAcquired'] = artworks.DateAcquired.dt.year
artworks['YearAcquired'].dtype

dtype('int64')

Great. Let's do some more miscellaneous cleaning.

In [8]:
# Remove multiple nationalities, genders, and artists.
artworks.loc[artworks['Gender'].str.contains('\) \('), 'Gender'] = '\(multiple_persons\)'
artworks.loc[artworks['Nationality'].str.contains('\) \('), 'Nationality'] = '\(multiple_nationalities\)'
artworks.loc[artworks['Artist'].str.contains(','), 'Artist'] = 'Multiple_Artists'

# Convert dates to start date, cutting down number of distinct examples.
artworks['Date'] = pd.Series(artworks.Date.str.extract(
    '([0-9]{4})', expand=False))[:-1]

# Final column drops and NA drop.
X = artworks.drop(['Department', 'DateAcquired', 'Artist', 'Nationality', 'Date'], 1)

# Create dummies separately.
artists = pd.get_dummies(artworks.Artist)
nationalities = pd.get_dummies(artworks.Nationality)
dates = pd.get_dummies(artworks.Date)

# Concat artists with other variables
X = pd.get_dummies(X, sparse=True)
X = pd.concat([X, nationalities, dates], axis=1)

Y = artworks.Department

# Alright! We've done our prep, let's build the model.
# Neural networks are hugely computationally intensive.
# This may take several minutes to run.

# Import the model.
from sklearn.neural_network import MLPClassifier

# Establish and fit the model, with a single, 1000 perceptron layer.
mlp = MLPClassifier(hidden_layer_sizes=(1000,))
mlp.fit(X, Y)

In [9]:
mlp.score(X, Y)

NameError: name 'mlp' is not defined

In [ ]:
Y.value_counts()/len(Y)

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

Now we got a lot of information from all of this. Firstly we can see that the model seems to overfit, though there is still so remaining performance when validated with cross validation. This is a feature of neural networks that aren't given enough data for the number of features present. _Neural networks, in general, like_ a lot _of data_. You may also have noticed something also about neural networks: _they can take a_ long _time to run_. Try increasing the layer size by adding a zero. Feel free to interrupt the kernel if you don't have time...

Also note that we created bools for artist's name but left them out. Both of the above points are the reason for that. It would take much longer to run and it would be much more prone to overfitting.

## Model parameters

Now, before we move on and let you loose with some tasks to work on the model, let's go over the parameters.

We included one parameter: hidden layer size. Remember in the previous lesson, when we talked about layers in a neural network. This tells us how many and how big to make our layers. Pass in a tuple that specifies each layer's size. Our network is 1000 neurons wide and one layer. (100, 4, ) would create a network with two layers, one 100 wide and the other 4.

How many layers to include is determined by two things: computational resources and cross validation searching for convergence. It's generally less than the number of input variables you have.

You can also set an alpha. Neural networks like this use a regularization parameter that penalizes large coefficients just like we discussed in the advanced regression section. Alpha scales that penalty.

Lastly, we'll discuss the activation function. The activation function determines whether the output from an individual perceptron is binary or continuous. By default this is a binary function ('relu', or 'rectified linear unit function'). In the exercise we went through earlier we used this binary function, but we discussed the _sigmoid_ as a reasonable alternative. The _sigmoid_ (called 'logistic' by SKLearn because it's a 'logistic sigmoid function') allows for continuous variables between 0 and 1, which allows for a more nuanced model. It does come at the cost of increased computational complexity.

If you want to learn more about these, study [activation functions](https://en.wikipedia.org/wiki/Activation_function) and [multilayer perceptrons](https://en.wikipedia.org/wiki/Multilayer_perceptron). The [Deep Learning](http://www.deeplearningbook.org/) book referenced earlier goes into great detail on the linear algebra involved.

You could also just test the models with cross validation. Unless neural networks are your specialty cross validation should be sufficient.

For the other parameters and their defaults, check out the [MLPClassifier documentaiton](http://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier).

## Drill: Playing with layers

Now it's your turn. Using the space below, experiment with different hidden layer structures. You can try this on a subset of the data to improve runtime. See how things vary. See what seems to matter the most. Feel free to manipulate other parameters as well. It may also be beneficial to do some real feature selection work...

In [10]:
# Your code here. Experiment with hidden layers to build your own model.

# Use 25% of the data to improve runtime.
offset = int(X.shape[0] * 0.25)
small_X, small_Y = X[:offset], Y[:offset]

In [11]:
# Create a df to store the results for comparison
results = {'Layer Sizes':[], 'Score':[], 'Average CV':[]}
columns = results.keys()
layer_comparison = pd.DataFrame(data=results, columns=columns)
layer_comparison

Empty DataFrame
Columns: [Layer Sizes, Score, Average CV]
Index: []

In [12]:
from sklearn.neural_network import MLPClassifier

# Using 100,4 
mlp = MLPClassifier(hidden_layer_sizes=(100,4,))
mlp.fit(small_X, small_Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 4), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [13]:
score = mlp.score(small_X, small_Y)
print(score)

0.936595959204


In [14]:
small_Y.value_counts()/len(small_Y)

Prints & Illustrated Books    0.777213
Architecture & Design         0.222787
Name: Department, dtype: float64

In [15]:
from sklearn.model_selection import cross_val_score
cv = cross_val_score(mlp, small_X, small_Y, cv=5)
print(cv)
cv.mean()

[ 0.87785964  0.77723924  0.95404305  0.77719604  0.91041303]


0.85935019977213367

In [16]:
# Store the data in the model_comparison table
results = {'Layer Sizes':['100,4'], 'Score':[score], 'Average CV':[cv.mean()]}
layer_comparison = layer_comparison.append(pd.DataFrame(data=results, columns=results.keys()), ignore_index=True)

In [17]:
# Using 50,50 
mlp = MLPClassifier(hidden_layer_sizes=(50,50,))
mlp.fit(small_X, small_Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(50, 50), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [18]:
score = mlp.score(small_X, small_Y)
print(score)

0.94772559817


In [19]:
small_Y.value_counts()/len(small_Y)

Prints & Illustrated Books    0.777213
Architecture & Design         0.222787
Name: Department, dtype: float64

In [20]:
from sklearn.model_selection import cross_val_score
cv = cross_val_score(mlp, small_X, small_Y, cv=5)
print(cv)
cv.mean()

[ 0.85304382  0.78596355  0.9427962   0.9635447   0.90188094]


0.88944584031928664

In [21]:
# Store the data in the model_comparison table
results = {'Layer Sizes':['50,50'], 'Score':[score], 'Average CV':[cv.mean()]}
layer_comparison = layer_comparison.append(pd.DataFrame(data=results, columns=results.keys()), ignore_index=True)

In [22]:
# Using 100,100 
mlp = MLPClassifier(hidden_layer_sizes=(100,100,))
mlp.fit(small_X, small_Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [23]:
score = mlp.score(small_X, small_Y)
print(score)

0.903478496917


In [24]:
small_Y.value_counts()/len(small_Y)

Prints & Illustrated Books    0.777213
Architecture & Design         0.222787
Name: Department, dtype: float64

In [25]:
from sklearn.model_selection import cross_val_score
cv = cross_val_score(mlp, small_X, small_Y, cv=5)
print(cv)
cv.mean()

[ 0.86913532  0.86603335  0.93116153  0.95404305  0.69555943]


0.86318653602210493

In [26]:
# Store the data in the model_comparison table
results = {'Layer Sizes':['100,100'], 'Score':[score], 'Average CV':[cv.mean()]}
layer_comparison = layer_comparison.append(pd.DataFrame(data=results, columns=results.keys()), ignore_index=True)

In [27]:
# Using 500, 
mlp = MLPClassifier(hidden_layer_sizes=(500,))
mlp.fit(small_X, small_Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(500,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [28]:
score = mlp.score(small_X, small_Y)
print(score)

0.878543452127


In [38]:
small_Y.value_counts()/len(small_Y)

Prints & Illustrated Books    0.777213
Architecture & Design         0.222787
Name: Department, dtype: float64

In [30]:
from sklearn.model_selection import cross_val_score
cv = cross_val_score(mlp, small_X, small_Y, cv=5)
print(cv)
cv.mean()

[ 0.59868166  0.83055448  0.90575916  0.96761683  0.92476246]


0.84547491812534281

In [31]:
# Store the data in the model_comparison table
results = {'Layer Sizes':['500'], 'Score':[score], 'Average CV':[cv.mean()]}
layer_comparison = layer_comparison.append(pd.DataFrame(data=results, columns=results.keys()), ignore_index=True)

In [32]:
# Using 50,50,50,
mlp = MLPClassifier(hidden_layer_sizes=(50,50,50,))
mlp.fit(small_X, small_Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(50, 50, 50), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [33]:
score = mlp.score(small_X, small_Y)
print(score)

0.946988792803


In [34]:
small_Y.value_counts()/len(small_Y)

Prints & Illustrated Books    0.777213
Architecture & Design         0.222787
Name: Department, dtype: float64

In [35]:
from sklearn.model_selection import cross_val_score
cv = cross_val_score(mlp, small_X, small_Y, cv=5)
print(cv)
cv.mean()

[ 0.87010469  0.87495153  0.93949971  0.97091332  0.86019003]


0.90313185742783231

In [36]:
# Store the data in the model_comparison table
results = {'Layer Sizes':['50,50,50'], 'Score':[score], 'Average CV':[cv.mean()]}
layer_comparison = layer_comparison.append(pd.DataFrame(data=results, columns=results.keys()), ignore_index=True)

In [37]:
layer_comparison

Layer Sizes     Score  Average CV
0       100,4  0.936596    0.859350
1       50,50  0.947726    0.889446
2     100,100  0.903478    0.863187
3         500  0.878543    0.845475
4    50,50,50  0.946989    0.903132

# Analysis:

### From the layer_comparison table, it can be concluded that the 50,50, layer sizes had the best combination of score and average CV when compared to the other layer sizes used in this drill. The 50,50, layer sizes produced two networks of fifty layers each.

### Note: Adding more layers will improve results if the relationships have higher degrees of non-linearity. 

### Note: If there is a sharp case of overfitting (result for number 0 in the table), decreasing the number of nodes will decrease the chances for overfitting.